- name: Initial deploy
  hosts: all
  tasks:
    - name: Container present
      community.docker.docker_container:
        name: travels
        state: started
        image: org.kie.kogito/travels:2.0.0-SNAPSHOT
        network_mode: host