- name: Initial deploy
  hosts: all
  tasks:
    - name: Container present
      community.docker.docker_container:
        name: travels
        state: started
        image: org.kie.kogito/travels:2.0.0-SNAPSHOT
        ports:
          - 9080:9080
        env:
          QUARKUS_INFINISPAN_CLIENT_SERVER_LIST: host.docker.internal:11222
          KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092