- name: Check connection with Docker
  hosts: all
  tasks:
    - name: Container present
      community.docker.docker_container:
        name: tools_awx_1
        state: present
        image: ghcr.io/ansible/awx_devel:devel