- name: Check connection with Openshift
  tasks:
    - name: Check k8s namespace
      redhat.openshift.k8s:
        name: cnicolai-dev
        api_version: v1
        kind: Namespace
        state: present