- name: Restart container
  hosts: all
  tasks:
    - name: Restart container
      community.docker.docker_container:
        name: travels
        image: org.kie.kogito/travels:sale
        state: started
        network_mode: bridge
        restart: true