- name: Revert release
  hosts: all
  tasks:
    - name: Deploy older release
      community.docker.docker_container:
        name: travels
        state: present
        image: org.kie.kogito/travels:2.0.0-SNAPSHOT
        network_mode: default
        ports:
          - "9280:8280"