- name: Release sale event
  hosts: all
  tasks:
    - name: Deploy container
      community.docker.docker_container:
        name: travels
        state: present
        image: org.kie.kogito/travels:sale
        network_mode: host
        published_ports:
          - 9080