- name: Release sale event
  hosts: all
  tasks:
    - name: Deploy container
      community.docker.docker_container:
        name: travels
        state: started
        image: org.kie.kogito/travels:sale
        ports:
          - 9080:9080
        env:
          QUARKUS_INFINISPAN_CLIENT_SERVER_LIST: host.docker.internal:11222
          KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092